# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI (npm)
permissions:
  contents: read

on:
  workflow_dispatch:
  # pull_request:
  #   branches: ['main']
  push:
  # branches: ["never"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Show npm config
        run: npm config list

      - name: Install dependencies
        run: npm ci

      - name: List dependencies
        run: npm --loglevel verbose list

      - name: Setup Playwright
        run: npx playwright install

      - name: Run prettier check
        run: npm run prettier:check

      - name: Run lint
        run: npm run lint

      # - name: Run tests
      #   run: npm run test

      - name: Run tests for Codecov Test Analytics
        run: npm run test:codecov

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Run tests
      #   run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
